# {{ item.name }}

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN set -ex && \
	sed -i \
		-e 's@^mirrorlist@#mirrorlist@' \
		-e 's@#baseurl@baseurl@' \
		-e 's@mirror\.@vault.@' \
		/etc/yum.repos.d/CentOS-*.repo && \
	yum makecache && \
	yum --assumeyes install \
		python3 \
		python3-devel \
		bash \
		iproute \
		sudo
