---
lint: |
  set -e
  flake8
  yamllint .
  ansible-lint
dependency:
  name: "galaxy"
driver:
  name: "docker"
platforms:
  -
    name: "centos-7"
    image: "docker.io/library/centos:centos7"
    pre_build_image: false
provisioner:
  name: "ansible"
  config_options:
    defaults:
      interpreter_python: "auto_silent"
      remote_tmp: "/tmp"
  log: true
verifier:
  name: "ansible"
