---
lint: |
  set -e
  flake8
  yamllint .
  ansible-lint
dependency:
  name: "galaxy"
driver:
  name: "docker"
platforms:
  -
    name: "centos-7"
    image: "quay.io/centos/centos:centos7"
    pre_build_image: false
provisioner:
  name: "ansible"
  config_options:
    defaults:
      interpreter_python: "/usr/bin/python3"
      remote_tmp: "/tmp"
verifier:
  name: "ansible"
